[project]
name = "cv-project-match"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "langchain>=1.4.2",
    "langchain-community>=0.4.2",
    "langchain-openai>=1.6.6",
    "langchain-postgres>=0.0.18",
    "langchain-text-splitters>=1.1.2",
    "pandas>=3.0.6",
    "pdfplumber>=0.11.10",
    "psycopg[binary]>=3.3.6",
    "pydantic-settings>=2.15.0",
    "pymupdf>=1.28.2",
    "pymupdf4llm>=1.28.2",
    "python-docx>=1.2.0",
    "python-multipart>=0.0.32",
    "rank-bm25>=0.2.2",
    "snowballstemmer>=3.1.1",
    "uvicorn[standard]>=0.54.0",
]
